repos:
  - repo: local
    hooks:
      - id: ruff
        name: Format with ruff
        entry: poetry run ruff format
        language: system
        types: [python]

      - id: ruff-check
        name: Check with ruff
        entry: poetry run ruff check
        language: system
        types: [python]
