name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - run: python -m pip install poetry
      - run: poetry install
      - run: poetry run ruff check
        env:
          FORCE_COLOR: 1

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - run: python -m pip install poetry
      - run: poetry install
      - run: ./run_tests.sh
